version: "3.9"
services:
  db:
    image: postgres:14
    ports:
      - 5455:5432
    volumes:
      - ./sql:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: chenson
      POSTGRES_PASSWORD: chenson
      POSTGRES_DB: chenson

  redis:
    image: redis:alpine
    entrypoint: redis-server --appendonly yes --replica-read-only no --requirepass $REDIS_PASSWORD --maxmemory 512mb --maxmemory-policy allkeys-lru
    ports:
      - "6381:6379"
    expose:
      - "6379"
    env_file:
      - .env
