"""add ondelete

Revision ID: 298618e79eb7
Revises: 52d173aba8bb
Create Date: 2024-01-09 18:05:28.942158

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '298618e79eb7'
down_revision: Union[str, None] = '52d173aba8bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_order_items_product_id_products', 'order_items', type_='foreignkey')
    op.create_foreign_key(op.f('fk_order_items_product_id_products'), 'order_items', 'products', ['product_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint('fk_orders_address_info_id_addresses_info', 'orders', type_='foreignkey')
    op.create_foreign_key(op.f('fk_orders_address_info_id_addresses_info'), 'orders', 'addresses_info', ['address_info_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_orders_address_info_id_addresses_info'), 'orders', type_='foreignkey')
    op.create_foreign_key('fk_orders_address_info_id_addresses_info', 'orders', 'addresses_info', ['address_info_id'], ['id'])
    op.drop_constraint(op.f('fk_order_items_product_id_products'), 'order_items', type_='foreignkey')
    op.create_foreign_key('fk_order_items_product_id_products', 'order_items', 'products', ['product_id'], ['id'])
    # ### end Alembic commands ###
